name: test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    name: nvim ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [v0.10.4, stable, nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.version }}
      - run: nvim --headless -u NORC +'luafile tests/run.lua'
